### ISSUE TITLE
return the associated public key in the url

### ISSUE THREAD

**Issue by resession** [RangerMauve/hypercore-fetch#26]
with a post request using ipfs, the cid is return in the url, i think it would be great if we can do the same thing with hypercore-fetch. for example, `PUT hyper://test/test.txt` should return `hyper://somePubKeyHere/test.txt`. as of right now, we can get the pubkey from the `Link` header but returning it with the url seems more direct and easier.

**Comment by RangerMauve** [comment]
Out in the latest version!
