### ISSUE TITLE
What characters may be used in a namespace petname?

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#35]

**Comment by RangerMauve** [comment]
Once we release the new version any characters that can be decoded by the querystring parameter can be used, so pretty much any unicode characters.

At the moment, only characters that can go into the `hostname` portion of a URL, and excluding `.` (which triggers a DNS lookup).

Generally, I'd suggest sticking to letters/numbers with underscores.

**Comment by josephmturner** [comment]
Thank you!!
