### ISSUE TITLE
Last-Modified header missing

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#48]
Files created with `PUT` requests should have a `Last-Modified` header, but they currently do not.

**Comment by RangerMauve** [comment]
Just to clarify, the `Last-Modified` header should be getting set on the response to a `GET` on the file and it currently isn't right?

**Comment by RangerMauve** [comment]
Found the bug. This also affected the `HEAD` requests.

Maybe TypeScript types would have caught this issue early on. :P

**Comment by RangerMauve** [comment]
Fixed in hypercore-fetch@9.0.6 and out in hyper-gateway@3.0.3

**Comment by josephmturner** [comment]
Thanks! I can confirm this is no longer an issue.
