### ISSUE TITLE
Should `'Range'` header be set somewhere?

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#50]
What is the purpose of the `'Range'` and `'Content-Range'` headers? I don't see that the `'Range'` header is set anywhere.

**Comment by josephmturner** [comment]
Which headers should provide the same information which previously was provided by the `X-Blocks` and `X-Blocks-Downloaded` headers?

**Comment by RangerMauve** [comment]
`Range` is set on the client side to load chunks of a file. 'Content-Rage` is there to let the client know that that the Range request was satisfied and which data got loaded. `Accept-Ranges` is how the server lets the client know that range requests may be made.

There currently isn't an equivalent to the `X-Blocks` and `X-Blocks-Downloaded` headers. I'm down to add them back in though!

**Comment by josephmturner** [comment]
Thank you for the explanation!

> There currently isn't an equivalent to the `X-Blocks` and `X-Blocks-Downloaded` headers. I'm down to add them back in though!

Yes, please!! :)

**Comment by josephmturner** [comment]
Made an issue for it: https://github.com/RangerMauve/hypercore-fetch/issues/53

**Comment by RangerMauve** [comment]
Let's close this in favor of the new issue
