### ISSUE TITLE
Expose MOUNT and UNMOUT methods

### ISSUE THREAD

**Issue by RangerMauve** [RangerMauve/hypercore-fetch#6]
There should be a way to mount hyperdrives onto your hyperdrive.

I propose something like

```
MOUNT /path/to/dir {body: 'hyper://tomount'} => 200 OK
UNMOUNT /path/to/dir => 200 OK
```

You can specify the path you want to mount at (the parent folders will get auto-created), and specify the `hyper://` URL you want mounted in there.

You can remove a mount by using UNMOUNT and the path to the mount.

**Comment by KyGost** [comment]
Closed?
Decided this will go elsewhere?

**Comment by RangerMauve** [comment]
Whoops!

**Comment by RangerMauve** [comment]
the latest version of hyperdrive does not have this anymore
