### ISSUE TITLE
Adjusting HTTP response for various hyperdrive statuses

### ISSUE THREAD

**Issue by alphapapa** [RangerMauve/hypercore-fetch#61]
Hi Mauve,

@josephmturner  and I were talking about how to distinguish various cases when requesting information about a hyperdrive, and we came up with this matrix of what would be ideal for the application side of the protocol.  Would it be possible for hyper-gateway and/or hypercore-fetch to provide responses like these?

# Response matrix

Currently observed behavior.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Request for</th>
<th scope="col" class="org-left">Returns</th>
<th scope="col" class="org-left">#</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">URL to valid hyperdrive without content</td>
<td class="org-left">Etag == 1</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">URL to unknown (i.e. network-inaccessible) hyperdrive</td>
<td class="org-left">Etag == 1</td>
<td class="org-left">!</td>
</tr>

<tr>
<td class="org-left">URL to valid hyperdrive that has ever had content</td>
<td class="org-left">Etag &gt; 1</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">URL to valid hyperdrive directory but invalid file</td>
<td class="org-left">HTTP 404</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">URL with too-short public key</td>
<td class="org-left">HTTP 500</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

<a id="org369d002"></a>

## Ideals?

What we'd ideally like the behavior to be.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Request for</th>
<th scope="col" class="org-left">HTTP</th>
<th scope="col" class="org-left">Etag</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Obviously malformed URLs</td>
<td class="org-left">400 Bad Request</td>
<td class="org-left">N/A</td>
</tr>

<tr>
<td class="org-left"><a href="#orgdb90c35">Unknown hyperdrive</a></td>
<td class="org-left">404 Not Found</td>
<td class="org-left">N/A</td>
</tr>

<tr>
<td class="org-left"><a href="#orge4b8627">Known hyperdrive (never had content)</a></td>
<td class="org-left">204 No Content</td>
<td class="org-left">N/A</td>
</tr>

<tr>
<td class="org-left">Known hyperdrive (has or had content)</td>
<td class="org-left">200 OK</td>
<td class="org-left">&gt;= 1</td>
</tr>
</tbody>
</table>

To distinguish whether peers are available, ideally we would use another header, something like `X-Hyperdrive-Peers`.

<a id="orgcd04931"></a>

## Glossary

<a id="orgdb90c35"></a>

### Unknown hyperdrive

An unknown hyperdrive may or may not exist.  We don't know whether it does.  We have never received any information about it.

<a id="orge4b8627"></a>

### Known hyperdrive (never had content)

A hyperdrive that we know exists, and we know it is empty, and it has never yet had any content.  Possibly created by us.

**Comment by josephmturner** [comment]
What should the expected `etag` be for unknown hyperdrives with no peers?

**Comment by RangerMauve** [comment]
Looks like right now invalid drives or unknown drives end up creating a new key which is a bug.

**Comment by RangerMauve** [comment]
SHould double check if this is still the case

**Comment by josephmturner** [comment]
See https://github.com/RangerMauve/hypercore-fetch/issues/60#issuecomment-1448863526
for handling POST requests to non-writable drives with 405 "You can't POST here"

**Comment by josephmturner** [comment]
> SHould double check if this is still the case

It still is. See #68.

**Comment by josephmturner** [comment]
Still TODO:
- [ ] Valid z32-encoded public key for which no drive is found should
  give 404 (current: 200)
- [ ] Known existent drive with no content should return 204 (current: 200)
- [ ] Show available peers in `X-Hyperdrive-Peers` header (move this to another issue?)

**Comment by RangerMauve** [comment]
What does known existent with no content mean in this context? Is that  when the hyperdrive header is there but there are no files (.e.g length = 0)

**Comment by RangerMauve** [comment]
Also yes please move the x-hyperdrive-peers to another issue. I think it might be good to place that into another `$/peers` endpoint or similar.

**Comment by josephmturner** [comment]
> What does known existent with no content mean in this context? Is that when the hyperdrive header is there but there are no files (.e.g length = 0)

Yes.

**Comment by RangerMauve** [comment]
Have a new issue for the peers thing, #74 

Not gonna bother with a special case for empty valid drives for now.

404 on drives without initial metadata block is in place in latest version
