### ISSUE TITLE
Should it be possible to put a file at the root url?

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#64]
Currently, it is possible to put a file at the root of a hyperdrive, so that `hyper://PUBLIC-KEY` points to a file (while `hyper://PUBLIC-KEY/` points to the root directory). I think this is an extension of #40, but this specific case seems highly likely to confuse users.

**Comment by RangerMauve** [comment]
This should not be possible. Maybe it's taking the `/` as a file name?

**Comment by RangerMauve** [comment]
I'll just account for this and throw an error.

**Comment by alphapapa** [comment]
To be clear, this means that hyperdrive allows a filename to be the empty string?

**Comment by RangerMauve** [comment]
Seems so. I think they just take any arbitrary string as the name. Might be worthwhile to open an issue on the hyperdrive-next repo?

**Comment by alphapapa** [comment]
Yeah, it seems like allowing a filename to be the empty string is at least an oversight.  I don't know of any other filesystems or HTTP servers that would allow that.

**Comment by josephmturner** [comment]
> Seems so. I think they just take any arbitrary string as the name. Might be worthwhile to open an issue on the hyperdrive-next repo?

https://github.com/holepunchto/hyperdrive-next/issues/43

**Comment by RangerMauve** [comment]
I think we added some code to handle this case
