### ISSUE TITLE
How to get next hyperdrive version for an entry

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#72]
It is currently possible to navigate backwards through the history of a hyperdrive entry by checking the `ETag` returned in the `HEAD`/`GET` response header, decrementing that `ETag`, then loading the previous version (`hyper://PUBLIC-KEY/$/version/ETAG-1/file.txt`).

How can we load the next version of a hyperdrive entry? For "directories", this is as simple as incrementing the `ETag`. IIUC, for files we have to iterate through `ETag`s going forward from current version. Is there a more practical solution?

**Comment by alphapapa** [comment]
Thanks.
